#!/usr/bin/env bash
# Install Nix, devenv, and cachix.
# This is a thin wrapper around https://github.com/mcdonc/devenv-bootstrap
set -euo pipefail
BOOTSTRAP_URL="https://raw.githubusercontent.com/mcdonc/devenv-bootstrap/main/bootstrap.py"
exec python3 <(curl -sSf "$BOOTSTRAP_URL") "$@"
